# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  - devops

resources:
  - repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: "b65fed88-5f25-4ab6-9242-0a6e22864dab"
  imageRepository: "remixenterprisestarter"
  containerRegistry: "droopycontainers"
  latestImage: $(containerRegistry).azurecr.io/$(imageRepository):latest
  dockerfilePath: "$(Build.SourcesDirectory)/Dockerfile"
  tag: "$(Build.BuildId)"

  # Agent VM image name
  vmImageName: "ubuntu-latest"

stages:
  - stage: Build
    displayName: Build and push
    jobs:
      
      - job: build_and_push
        displayName: Build and push custom docker image
        pool:
          vmImage: $(vmImageName)
        steps:

        - task: Docker@2
          inputs:
            containerRegistry: 'droopycontainers'
            repository: 'remixenterprisestarter'
            command: 'buildAndPush'
            Dockerfile: '**/Dockerfile'
            tags: |
              $(Build.BuildId)
              latest