# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  - devops

resources:
  - repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: "b65fed88-5f25-4ab6-9242-0a6e22864dab"
  imageRepository: "remixenterprisestarter"
  containerRegistry: "droopycontainers"
  latestImage: ${containerRegistry}.azurecr.io/${imageRepository}:latest
  dockerfilePath: "$(Build.SourcesDirectory)/Dockerfile"
  tag: "$(Build.BuildId)"

  # Agent VM image name
  vmImageName: "ubuntu-latest"

stages:
  - stage: Build
    displayName: Build and push stage
    jobs:
      - job: load_cache
        displayName: Load cached docker layers
        pool:
          vmImage: $(vmImageName)
        steps: 
          - task: Docker@2
            inputs:
              containerRegistry: '${dockerRegistryServiceConnection}'
              command: 'login'

          - script: "docker pull ${latestImage}"
            displayName: Pull latest for layer caching
            continueOnError: true # for first build, no cache
        
      - job: build_and_push
        displayName: Build
        pool:
          vmImage: $(vmImageName)
        steps:
        - task: Docker@2
          inputs:
            containerRegistry: '${dockerRegistryServiceConnection}'
            repository: '${imageRepository}'
            command: 'build'
            Dockerfile: '**/Dockerfile'
            arguments: '--cache-from=${latestImage}'

        - task: Docker@2
          inputs:
            containerRegistry: '${dockerRegistryServiceConnection}'
            repository: '${imageRepository}'
            command: 'push'
