trigger:
  - devops

variables:
  npmCacheDir: "/home/vsts/.npm"

jobs:
  - job:
    displayName: Build and Archive and Publish Artifacts
    pool:
      vmImage: ubuntu-latest
    steps:
      - task: NodeTool@0
        displayName: Install Node 16
        inputs:
          versionSpec: "16.x"

      - task: Cache@2
        inputs:
          key: '"npm" | "$(Agent.OS)" | package.json'
          path: $(npmCacheDir)
        displayName: Cache NPM packages

      - script: |
          npm install
        displayName: Install dependencies

      - script: |
          npm run lint
          npm run build
          npm run build:ladle
        displayName: "Lint and build"

      - script: |
          rm -rf node_modules
          mkdir temp
          cd temp
          npm install @remix-run/serve 
          cd ..
          mkdir node_modules
          mv temp/node_modules/* node_modules
        displayName: "Delete all node_modules except remix-serve"

      - task: ArchiveFiles@2
        displayName: Archive
        inputs:
          rootFolderOrFile: "$(Build.SourcesDirectory)"
          includeRootFolder: false
          archiveType: "zip"
          archiveFile: "$(Build.ArtifactStagingDirectory)/web-$(Build.BuildNumber).zip"
          replaceExistingArchive: true

      - task: PublishBuildArtifacts@1
        displayName: Publish Artifacts
        inputs:
          PathtoPublish: "$(Build.ArtifactStagingDirectory)"
          ArtifactName: "drop"
          publishLocation: "Container"
