# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  - devops

resources:
  - repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: "b65fed88-5f25-4ab6-9242-0a6e22864dab"
  imageRepository: "remixenterprisestarter"
  containerRegistry: "droopycontainers"
  latestImage: $(containerRegistry).azurecr.io/$(imageRepository):latest
  dockerfilePath: "$(Build.SourcesDirectory)/Dockerfile"
  tag: "$(Build.BuildId)"

  # Agent VM image name
  vmImageName: "ubuntu-latest"

stages:
  - stage: Build
    displayName: Build and push stage
    jobs:
        
      - job: build_and_push
        displayName: Build
        pool:
          vmImage: $(vmImageName)
        steps:
        - task: Docker@2
          displayName: "login to container registry"
          inputs:
            containerRegistry: b65fed88-5f25-4ab6-9242-0a6e22864dab
            command: 'login'

        - script: "docker pull $(latestImage)"
          displayName: Pull latest for layer caching
          continueOnError: true # for first build, no cache
        - task: Docker@2
          displayName: "build dockerfile"
          inputs:
            containerRegistry: b65fed88-5f25-4ab6-9242-0a6e22864dab
            repository: '$(imageRepository)'
            command: 'build'
            Dockerfile: '**/Dockerfile'
            arguments: '--cache-from=$(latestImage)'

        - task: Docker@2
          displayName: "Push docker images"
          inputs:
            containerRegistry: b65fed88-5f25-4ab6-9242-0a6e22864dab
            repository: '$(imageRepository)'
            command: 'push'
