trigger:
  - manual

variables:
  npmCacheDir: "/home/vsts/.npm"
  buildFiles: "app/**, env/**, styles/**, public/**, package.json"

jobs:
  - job: buildandcache
    dependsOn: dependencies
    displayName: build
    pool:
      vmImage: ubuntu-latest
    steps:
      - task: NodeTool@0
        displayName: Install Node 16
        inputs:
          versionSpec: "16.x"
      
      - task: Cache@2
        displayName: Cache node_modules
        inputs:
          key: '"dependencies" | "$(Agent.OS)" | package.json'
          path: node_modules
          cacheHitVar: NODE_MODULES_CACHE_HIT
          
      - task: Cache@2
        displayName: "Cache server build"
        inputs:
          key: '"server-build" | "$(Agent.OS)" | $(buildFiles)'
          path: build
          cacheHitVar: SERVER_BUILD_CACHE_HIT

      - task: Cache@2
        displayName: "Cache browser build"
        inputs:
          key: '"browser-build" | "$(Agent.OS)" | $(buildFiles)'
          path: public/build
          cacheHitVar: BROWSER_BUILD_CACHE_HIT

      - script: |
          npm install
        condition: eq(variables.NODE_MODULES_CACHE_HIT, 'false')
        displayName: Install dependencies
      
      - script: |
          npm run lint
          npm run build
        condition:  or(eq(variables.SERVER_BUILD_CACHE_HIT, 'false'), eq(variables.BROWSER_BUILD_CACHE_HIT, 'false'))
        displayName: "Lint and build"
        
      - script: |
          rm -rf node_modules
        displayName: "Lint and build"